apiVersion: batch/v1
kind: Job
metadata:
  name: nklee-batch
spec:
  template:
    spec:
      containers:
      - name: nklee-batch
        image: python:3.7
        command: ["python3"]
      restartPolicy: Never
  backoffLimit: 4
