apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nklee-cron
spec:
  # minute, hour, day of the month, month, day of the week(0 - 6 : 0 is Sunday)
  schedule: '*/1 * * * *' 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nklee-cron
            image: python:3.7
            command: ["echo", "Running a job"]
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid # Allow, Forbid, Replace
