apiVersion: v1
kind: Service
metadata:
  labels:
    app: nklee-superset
  name: nklee-superset-svc
  namespace: default
spec:
  ports:
  - nodePort: 30800
    port: 8087
    protocol: TCP
    targetPort: 8088
  selector:
    app: nklee-superset
  type: NodePort
